image: markhobson/maven-chrome:jdk-17

stages:
  - build
  - test

build:
  stage: build
  script:
      - mvn clean
      - mvn compile

test:
  stage: test
  script:
      - mvn verify
  artifacts:
    when: always
    paths:
      - src/videos/**/*.mp4
      - src/screenshots/**/*.png
    expire_in: 1 week
