image: markhobson/maven-chrome:jdk-11

stages:
  - build
  - test

build-job:
  stage: build
  script:
      - mvn clean
      - echo "Previous artifacts have been cleaned!"
      - mvn compile
      - echo "The package is compilied!"

test-job:
  stage: test
  script:
      - echo "The implemented tested are being run!"
      - mvn test
      



